name: Continuous Integration
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Build web image
        run: docker build -t toohakai/web:latest -f ./apps/web/Dockerfile .

      - name: Build server image
        run: docker build -t toohakai/server:latest -f ./apps/server/Dockerfile .

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./apps/cms/docker/staging/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/website/cms:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/website/cms:latest

