name: Continuous Deployment
on:
  push:
jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      #      - name: Build
      #        run: pnpm run build

      #      - name: Build web image
      #        run: docker build -t toohakai/web:latest -f ./apps/web/Dockerfile .
      #
      #      - name: Build server image
      #        run: docker build -t toohakai/server:latest -f ./apps/server/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: server - build and push to ghcr
        uses: docker/build-push-action@v4
        with:
          file: ./apps/server/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/toohakai/server:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/toohakai/server:latest

      - name: web - build and push to ghcr
        uses: docker/build-push-action@v2
        env:
          NEXT_PUBLIC_TOOHAKAI_API_URL: "https://api.toohakai.fun"
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        with:
          file: ./apps/web/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/toohakai/web:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/toohakai/web:latest
